### ISSUE TITLE
Probably need minRate and maxRate for telemetry rather than just rate

### ISSUE THREAD

**Issue by tmtsoftwareadmin** [tmtsoftware/icd#10]
I see some of the ICD provide a lower and upper bound for the rate.  This might be better to have a minRate and maxRate that could be set to the same by default.

**Comment by abrighton** [comment]
The current icd schema has minRate and maxRate (floats). 
The default values are 0, which is interpreted to mean "not set" in this case.
(The pdf and web app displays only display the values if they were set to some non-zero value).
