### ISSUE TITLE
Add a REST interface to the web application.

### ISSUE THREAD

**Issue by tmtsoftwareadmin** [tmtsoftware/icd#18]
From dkerley in review comments:

In Section 9 the published/unpublished feature allows us to stage/test multiple changes to APIs before they get published. It could be quite useful if it were exposed through a REST API (e.g., enable a POST of one or more files to an “http://somewhere/api/test” resource). That way the local build process could include an API check using simple command-line utilities (curl) or something like shell/Python scripts. The http response could report back to the developer things like "Warning: local API subscribes to non-existent events stream BLA”, without having to click through pages in the web app.

We should add this feature.

**Comment by abrighton** [comment]
It should be possible to do much of this using the icd and icd-db command line applications.
It might be necessary to make some changes for ease of use in scripts.
I'll do some tests...

**Comment by abrighton** [comment]
I changed the icd command line app to exit(1) if validation fails. This should make it easier to use in a script or build file.

**Comment by abrighton** [comment]
I think the icd and icd-db command line apps provide the necessary features for this issue.
