### ISSUE TITLE
Render command arguments

### ISSUE THREAD

**Issue by edwardchapin** [tmtsoftware/icd#19]
Currently (414390de) icd-web does not seem to render command argument details. For example, in `examples/NFIRAOS/rtc/command-model.conf` the **CONFIGURE** command takes many possible arguments, but only the name and description fields are shown (both in the browser and in the rendered PDF). This might be sort of like Issue #14.

**Comment by abrighton** [comment]
Now the pdf and web layouts display the command arguments and other information.
