### ISSUE TITLE
Allow comparing two versions of a published ICD or API in the web application

### ISSUE THREAD

**Issue by tmtsoftwareadmin** [tmtsoftware/icd#22]
Assuming the diff functionality is already available, implement the ability for the user to see what is different between two versions of the same API or two versions of the same ICD.

If it seems to be difficult we should wait until some time in the future.

**Comment by abrighton** [comment]
There is now a Compare button under the version history table and checkboxes next to the version numbers. You can select two versions and compare them. The information that is displayed is like a UNIX "diff". It shows what you need to add or remove to get from one version to the other.
