### ISSUE TITLE
install ingest.sh

### ISSUE THREAD

**Issue by edwardchapin** [tmtsoftware/icd#29]
It would be nice if ingest.sh were installed in the same location as the other binaries (install_icd/bin/) to facilitate ICD work by subsystem developers. Probably also a good idea to rename the script to something less generic if it will end up in PATH (e.g., icd-ingest.sh).

**Comment by abrighton** [comment]
Done. I renamed it to icd-ingest.sh and it will be installed in the ../install_icd/bin dir.

**Comment by edwardchapin** [comment]
Thanks - just noticed one minor thing though. chmod complains for me (although it still seems to give me an executable script when installed):

chmod: invalid mode: ‘utg+x’

I'm guessing it's a BSD vs. GNU chmod implementation difference.

**Comment by abrighton** [comment]
Sorry, that was a typo: I fixed it.
