### ISSUE TITLE
Update subsystem.conf

### ISSUE THREAD

**Issue by tmtsoftwareadmin** [tmtsoftware/icd#3]
SE has changed the N2 diagram and the abbreviations of some subsystems.  The following changes are needed:

Add:
M1S // M1 Optics System
CRYO // Instrumentation Cryogenic Cooling System
REFR // Instrumentation Refrigerant Cooling System

Change M2 to M2S // M2 Optics System
Change M3 to M3S // M3 Optics System

**Comment by abrighton** [comment]
Made changes to subsystem.conf and updated examples.
