### ISSUE TITLE
Show warning when subscribed items do not exist

### ISSUE THREAD

**Issue by tnakamot** [tmtsoftware/icd#35]
Currently, when ICD tools (icd-db, icd-web, ...) ingest model files into Mongo DB, they do not show any warning even if subscribed items do not exist. Such inconsistency between two subsystems should be shown as warning, so that the designers can be notified of incompatible changes or typos.

**Comment by abrighton** [comment]
That makes sense. The command line tools could print warning messages for ICDs where subscribed items are missing a publisher. The web app could display a warning icon perhaps.

**Comment by tnakamot** [comment]
I think web app should show warning messages when model files are uploaded. This is an issue when ingesting or updating model files. It is not actually an error because, if someone uploads files one by one, subscribed items are missing, of course, when he uploads the first model file. 

In addition, yes, web app could display a warning icon if the subscribed items do not exist at the opponent side, or even prevent publishing a new ICD until such errors are resolved. Currently, such items are not just shown in web app without any warnings, and the designers have to carefully look at all the subscribed item lists to confirm if all intended items are shown there.

**Comment by abrighton** [comment]
I checked in changes to the current icd master branch so that warnings are displayed (in PDF and HTML versions) for subscribed items where there is no matching published item. You can search for the string "Warning: " to find them. The warnings are displayed where the missing publisher's "description" text would have been.

Adding the same warnings when importing the model files is a bit more complicated, but could be done.

**Comment by tnakamot** [comment]
Thank you for your change! I tried out icd-web-server in the master branch, and it worked fine, but there was one thing different from what I expected. The warning is now shown if the subscribed item does not exist *and* the opponent subsystem exists. This is cool, but I also expected the warning be shown even if the subsystem does not exist. Actually, this was the problem I encountered. I changed the name of one subsystem (subsystem A) from which another subsystem (subsystem B) subscribes one telemetry. I should have changed (or asked the designer of subsystem B) subscribe-model.conf in accordance with the name change of subsystem A, but I forgot to do that.

**Comment by abrighton** [comment]
Thanks for the feedback. I checked in a fix that displays the warnings also when the publisher subsystem is missing. I also added the same type of warning for "sent command configurations" where the receiving subsystem does not define them.

**Comment by tnakamot** [comment]
Thank you for your effort. I confirmed that icd-web and generated PDF show warning if the publisher subsystem does not exist. I also confirmed that warnings are shown for undefined commands. This is very nice and removes the great amount of time to seek what is missing!
