### ISSUE TITLE
units field does not handle html

### ISSUE THREAD

**Issue by kerleyd** [tmtsoftware/icd#36]
Can the units field be update to parse html like the description field does?

This example does not work for the units field, but does work for the description field:
`units = "&mu;m of RMS wavefront error in FCRS<sub>174.5</sub>"`

However using `<html></html>` does work for both fields:
`units   = "<html>&mu;m of RMS wavefront error in FCRS<sub>174.5</sub></html>"`
but these extra tags are not required for the description field

**Comment by abrighton** [comment]
I checked in a small change to the master branch of icd and tested your example and it displayed correctly in the web app and in pdf.
