### ISSUE TITLE
Heading numbering in ICD/API pdf

### ISSUE THREAD

**Issue by lianqiw** [tmtsoftware/icd#38]
The headings in the generated ICD and API pdf need to have numbering so that we can refer to the sections in word documents when using them as applicable documents. 

Also, each kind of interface between two components should be grouped in a section with heading numbers available. 

The heading number also needs to following TMT standards, like the following:
1
1.1
1.1.2
1.2
2
2.1

**Comment by abrighton** [comment]
In the current master branch, the API and ICD PDFs now have numbering.
