### ISSUE TITLE
Provide reporting on publish / subscribe event relationships

### ISSUE THREAD

**Issue by scroberts** [tmtsoftware/icd#43]
The following functionality is required to support ICD change requests:
- Report of components that are subscribing to events that don't have a publisher (orphans).
- Report of published events that don't have subscribers.
- Report of all subscribers to a published event. I.E. provide a list of stakeholders when a change is being proposed).
- Ability to see differences between two versions of an API. This will enable review of proposed changes, and using the above tools will enable check-in with stakeholders about proposed changes.

**Comment by edwardchapin** [comment]
As an extension to this, I would also add similar reports for commands:

  * Report of components that specify receive commands with no senders
  * Report of components that specify send commands to a component, but the component does not implement the command

**Comment by scroberts** [comment]
A thought: would it be possible for the ICD software to add hyperlinks that lead to "where used" reports for event and command names in API and ICD displays.  I.E. the reports would include who subscribes to the event names and who calls the commands.

**Comment by abrighton** [comment]
The current icd version does have these links in the web app. 
In the PDF output you have a list of subscribers for an event. For example:

    Events Published by imager-odgw-assembly
         imager-odgw-assembly publishes event: state
        Subscribers: TCS.cmIRIS

In the web app, "TCS.cmIRIS" is a link to the component description.

**Comment by edwardchapin** [comment]
I agree that you can click on individual things in the web view to get specific details, but some sort of summary report view would also be useful. 

My personal interest is probably more at the command-line level. If I change an event name, or remove a command (for example), I would like to quickly see all of the links I've broken (as well as things that lack a subscriber). If it's text in a terminal, it's easy to run before/after reports through diff to see what changed. Also breaking the reporting down by subsystem and assembly would be very helpful (maybe command line args).

**Comment by abrighton** [comment]
_* Report of components that are subscribing to events that don't have a publisher (orphans).
* Report of published events that don't have subscribers._

The report can be generated with the icd-db command and the --missing (-m) option. 

_* Report of all subscribers to a published event. I.E. provide a list of stakeholders when a change is being proposed)._

The subscribers are listed in the generated pdf and html.

_* Ability to see differences between two versions of an API. This will enable review of proposed changes, and using the above tools will enable check-in with stakeholders about proposed changes._

The latest version has improved support for comparing versions in the web app under the "History" tab.

_* Report of components that specify receive commands with no senders
* Report of components that specify send commands to a component, but the component does not implement the command_

This is also included in the output of the missing items report (icd-db -m).
