### ISSUE TITLE
Add an abstract TAI Julian Date data type (something like `struct timespec`)

### ISSUE THREAD

**Issue by edwardchapin** [tmtsoftware/icd#47]
There are a number of places (particularly ICDs involving the TCS) where it would be useful to have an abstract data type for representing precise absolute time stamps. Some recent discussions between IRIS and TCS, noted in a Slack discussion (Aug 11, 2016 in #sw-stakeholder-wg), propose Julian Dates in the TAI system (which increase monotonically), encoded using something like `struct timespec` which includes two integer components, one for the seconds, and another for the nanoseconds. See Section 2.5.1 in the current [TCS-IRIS ICD](https://docushare.tmt.org/docushare/dsweb/Get/Version-78710/ICD%20TCS-IRIS_CCR10-Release.pdf).

Even if this data type is not currently supported within CSW, it would be useful as part of the icd-db now to assist in the production of uniform ICDs, particularly for subsystems that are in their Final Design Phase (e.g., NFIRAOS). By abstracting away the encoding method, its implementation can be deferred to a later date.

**Comment by abrighton** [comment]
The latest version in the master branch no supports the type "taiDate":
Example: ```
  telemetry = [
    {
      name = logToFile
      description = "sensor XXX values logged to file enabled"
      archive = false
      attributes = [
        {
          name = enabled
          description = "True if logging to file is enabled"
          type = boolean
        }
        {
          name = filename
          description = "path and file name of the engineering log file"
          type = string
        }
        {
          name = date
          description = "a TAI date value"
          type = taiDate
        }
      ]
    }
```

**Comment by edwardchapin** [comment]
Thanks for adding this. However, as I was trying it out on some local model files, a question came to mind (perhaps best for Jimmy Johnson to answer, so I will repeat it on Slack): while this new data type gives us a method of encoding absolute time stamps with sufficiently high precision, what are the units? After reviewing a few sources (https://en.wikipedia.org/wiki/Time_standard, http://astropy.readthedocs.io/en/v0.3.2/time/index.html, http://starlink.eao.hawaii.edu/docs/sun211.htx/sun211ss425.html) I think there are a three concepts that need to be clarified: 

- **time system** (e.g., TAI, UT)
- **time representation** (e.g., modified julian day) 
- **time encoding** (i.e., how it is represented internally)

I think that your new **taiDate** could be interpreted as covering the first and last bullets (i.e., it specifically represents times measured in the TAI system, and it is encoded in a particular way). I *think* I am then free to choose a **time representation** for the units, e.g., "MJD" or "MJD / days" (my preference would be that the former become an officially recognized TMT unit, and it is implicitly measured in days, though time service method calls could potentially return measurments in seconds, or years, or whatever...).

Alternatively, perhaps you want a more generic fundamental time encoding type (more along the lines of `struct timespec`), e.g. **timeDate**, which simply encodes *any* time, and then for the units one would specify "MJD TAI".

**Comment by abrighton** [comment]
You can declare in your icd model files that an attribute is of type taiDate. That doesn't say anything about how it is implemented. I assume there will be a TaiDate class at some point for this purpose (or some documentation saying that it is a pair of longs). The units might not be important if the TaiDate class always stores the values as a pair of (seconds, milliseconds).
