### ISSUE TITLE
Warning message when component subscribes to non-existent component

### ISSUE THREAD

**Issue by edwardchapin** [tmtsoftware/icd#48]
Ingestion of `subscribe-model` files already catches errors when invalid subsystems are specified (at ingest time), and invalid event/telemetry names (as a message in generated tables: "Warning: X does not publish Events:Y").

However, there is no indication of a problem when an invalid *component* is specified. Here is an example error I had made:
```
subscribe {
  events = [
    {
      subsystem     = TCS
      component     = cmNfiraos
      name          = pwfsPosx
      requiredRate  = 20
    }
}
```
The problem is that `cmNfiraos` is an invalid component name, it is in fact `cmNFIRAOS`. I can see that it may be tricky to detect at ingestion time (like catching event name errors) since it would need to be a two-pass system (load everything in first, then go back and check for valid cross-references). However, it should be possible to handle this in the same was as event name errors in the output web page / PDF, indicating that subsystem X has no component Y.

**Comment by abrighton** [comment]
The code for ingesting the model files has not been updated to report non-existing components (That could cause problems if the other components were not ingested yet). However there is now a "Missing Items" report you can generate (in pdf, html or csv format) with "icd-db -a filename" that lists that information.
