### ISSUE TITLE
icdwebserver: requires restart when ICD view garbled

### ISSUE THREAD

**Issue by edwardchapin** [tmtsoftware/icd#58]
In our continuous integration system, we are regularly dropping and re-ingesting entire subsystems. It seems that the ICD view in the icdwebserver can get confused, and often items from other unrelated subsystems appear in the browser window.

For example, I was looking at the AOESW-NFIRAOS ICD after doing a lot of work, and noticed a bunch of IRIS assemblies appearing (that publish values used by AOESW, for example). I did note that the IRIS assembly names in the web view did not appear as blue links. So, I suspect there is some stale data in the web server. I believe that the generated PDFs are OK.

Unfortunately I don't have a minimal test case that I can provide you with. I simply noticed that restarting icdwebserver made the problem go away.

**Comment by abrighton** [comment]
It turns out this was caused by concurrent updates happening when you select, for example, the target subsystem before the selected source subsystem was done updating the UI. The fix was to disable the UI while the update is in progress.
