### ISSUE TITLE
Add a comment called usage to subscribe-info

### ISSUE THREAD

**Issue by tmtsoftwareadmin** [tmtsoftware/icd#7]
We need to have a text area so the subscribe can describe how it uses a published item.

I suggest usage or usageDescription (I don't want to use description or they will try to describe the published item.)

It should be one of the multi-line ones.  

BTW, I think all comments/descriptions should be the multi line ones.

**Comment by abrighton** [comment]
Now the subscribe items have a "usage" description in the schema and it is displayed beneath the description in the web app and icd-db pdf output.
