### ISSUE TITLE
For array type in attributes minimum and maximum do not show up in output

### ISSUE THREAD

**Issue by tmtsoftwareadmin** [tmtsoftware/icd#9]
I create something like this in an event stream. But neither option shows up in the range type area of the output.

    {
          name = wavelength
          description = "An array of distinct wavelengths with dispersion information."
          type = array
          minimum = 2
            maximum = 22
          minItems = 1
          maxItems = 30
          units = microns
          items = {
            type = number
            minimum = 2
            maximum = 22
          }
        }

**Comment by abrighton** [comment]
I worked on the type display.
The current TCS example input looks like this: 

```
        {
          name = wavelength
          description = "An array of distinct wavelengths with dispersion information. Note range is not clear."
          type = array
          minItems = 1
          maxItems = 30
          minimum = 0.5
          maximum = 0.6
          units = microns
          items = {
            type = float
          }
        }
```

and the type description is displayed as: 

   array of float (0.5 ≤ x ≤ 0.6)
